#####################################################################
# Basic Server & Authorization
#####################################################################

[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/exulizer/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    127.0.0.0/8
    10.0.0.0/8
    172.16.0.0/12
    192.168.0.0/16
    169.254.0.0/16
    FE80::/10
    FC00::/7
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    *://192.168.178.22 

[octoprint_compat]

[history]

[include octoeverywhere-system.cfg]

#####################################################################
# Features & Plugins
#####################################################################

[timelapse]
## Hier werden die fertigen Videos gespeichert
output_path: ~/printer_data/timelapse/
## Hier liegen die Einzelbilder während des Drucks (temporär)
frame_path: /tmp/timelapse/
## Der Pfad zum Programm, das das Video zusammenfügt
ffmpeg_binary_path: /usr/bin/ffmpeg

#####################################################################
# Update Manager & External Repositories
#####################################################################

[update_manager]
channel: dev
refresh_interval: 168

[update_manager mainsail]
type: web
channel: stable
repo: mainsail-crew/mainsail
path: /home/exulizer/mainsail
persistent_files:
    config.json

[update_manager mainsail-config]
type: git_repo
primary_branch: master
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/exulizer/mainsail-config
managed_services: klipper

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[update_manager Klippain-ShakeTune]
type: git_repo
primary_branch: main
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: /home/exulizer/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
managed_services: klipper

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Exulizer/svender3d_backup.git
managed_services: moonraker
primary_branch: main